ticket-1577 IMA Agent moved into it's own repository
skalenetwork/ima-agent pull request #1
Opened 2023-10-11 15:16 UTC by sergiy-skalelabs

This pull request is massive refactoring in IMA.  IMA Agent moved into it's own repository.
No new tests needed. Existing tests were split between two repositories: `IMA` and new `ima-agent`.
Also includes improvements to minimize disk space occupied by NPM modules as dependencies (https://github.com/skalenetwork/IMA/issues/1579).

2023-10-12 18:14 UTC, sergiy-skalelabs commented
Also includes improvements to minimize disk space occupied by NPM modules as dependencies (https://github.com/skalenetwork/IMA/issues/1579).

2023-10-16 16:42 UTC, DmytroNazarenko requested changes

2023-10-16 16:42 UTC, DmytroNazarenko commented on CODEOWNERS
> +/proxy/ @payvint
Update it, please

2023-10-16 16:42 UTC, DmytroNazarenko commented on .gitmodules
> +	#url = git@github.com:skalenetwork/IMA.git
Remove comments, please

2023-10-16 16:42 UTC, DmytroNazarenko commented on README.md
> +The IMA is still in active development and therefore should be regarded as _alpha software_. The development is still subject to further security hardening, testing, and breaking changes.
We can remove it

2023-10-16 16:42 UTC, DmytroNazarenko commented on README.md
> +The Agent is a Node JS application connecting the smart contracts on Mainnet with SKALE Chains.
Describe agent architecture only here

2023-10-16 16:42 UTC, DmytroNazarenko commented on README.md
> +ANSI colorizer for console and log output.
Is this still relevant?

2023-10-16 16:42 UTC, DmytroNazarenko commented on package.json
> +    "private": true,
Do we need npm publishing? Do we need `private`?

2023-10-16 16:42 UTC, DmytroNazarenko commented on src/IMA-CORE.md
> +# IMA Agemt Core module
Typo

2023-10-16 16:42 UTC, DmytroNazarenko commented on src/test/agentUnitTests.js
Maybe let's move this dir to root test folder?

2023-10-16 16:42 UTC, DmytroNazarenko commented on src/OBSERVER.md
Maybe rename it to SNB.md?

2023-10-16 17:39 UTC, sergiy-skalelabs commented on CODEOWNERS
> +/proxy/ @payvint
Done

2023-10-16 17:40 UTC, sergiy-skalelabs commented on README.md
> +The IMA is still in active development and therefore should be regarded as _alpha software_. The development is still subject to further security hardening, testing, and breaking changes.
Done

2023-10-16 17:40 UTC, sergiy-skalelabs commented on README.md
> +The Agent is a Node JS application connecting the smart contracts on Mainnet with SKALE Chains.
Done

2023-10-16 17:42 UTC, sergiy-skalelabs commented on README.md
> +ANSI colorizer for console and log output.
Done

2023-10-16 17:44 UTC, sergiy-skalelabs commented on package.json
> +    "private": true,
Done

2023-10-16 17:44 UTC, sergiy-skalelabs commented on src/IMA-CORE.md
> +# IMA Agemt Core module
Done

2023-10-16 17:45 UTC, sergiy-skalelabs commented on src/test/agentUnitTests.js
Yes, agree

2023-10-16 17:46 UTC, sergiy-skalelabs commented on src/OBSERVER.md
Done

2023-10-16 17:56 UTC, sergiy-skalelabs commented on .gitmodules
> +	#url = git@github.com:skalenetwork/IMA.git
Done

2023-10-16 17:58 UTC, sergiy-skalelabs commented on src/test/agentUnitTests.js
Done

2023-10-16 19:50 UTC, DmytroNazarenko approved these changes

2023-11-06 17:33 UTC, dmytrotkk approved these changes

2023-11-06 17:34 UTC, merged