Ticket 98 type script less any
skalenetwork/ima-agent pull request #101
Opened 2024-03-11 15:55 UTC by sergiy-skalelabs

Massively removing `any`-kwyword usage from **TypeScript** code.
No new features introduced.
No performance changes expected.
No new tests needed.

2024-03-22 09:50 UTC, DmytroNazarenko approved these changes

2024-03-22 09:50 UTC, DmytroNazarenko commented on src/imaEventLogScan.ts
> +    if( ( idxAttempt + 1 ) > cntAttempts && ( !ret ) ) {
Remove redundant `()`

2024-03-22 09:50 UTC, DmytroNazarenko commented on src/loopWorker.ts
> +        function( joMessage: state.TLoadedJSON, joAnswer: any,
use object instead of any

2024-03-22 09:50 UTC, DmytroNazarenko commented on src/oracle.ts
> +    oracleOpts: TOracleOptions, details: log.TLogger
Use log.TLoggerBase instead

2024-03-22 09:50 UTC, DmytroNazarenko commented on src/state.ts
> +export function setPreventExitAfterLastAction( isPrevent?: boolean | null ): void {
Redundant null

2024-03-22 09:50 UTC, DmytroNazarenko commented on src/eventDispatcher.ts
> +export type TData = any;
Use object instead of any

2024-03-22 09:50 UTC, DmytroNazarenko commented on src/imaTx.ts
> +export declare type TPayedCallMethodArgument = any;
Try to replace any

2024-03-22 09:51 UTC, DmytroNazarenko requested changes
Need to fix issues above

2024-03-27 15:29 UTC, sergiy-skalelabs commented on src/imaEventLogScan.ts
> +    if( ( idxAttempt + 1 ) > cntAttempts && ( !ret ) ) {
fixed

2024-03-27 15:37 UTC, sergiy-skalelabs commented on src/oracle.ts
> +    oracleOpts: TOracleOptions, details: log.TLogger
fixed

2024-03-27 15:38 UTC, sergiy-skalelabs commented on src/state.ts
> +export function setPreventExitAfterLastAction( isPrevent?: boolean | null ): void {
fixed

2024-03-27 16:59 UTC, sergiy-skalelabs commented on src/eventDispatcher.ts
> +export type TData = any;
fixed

2024-03-27 17:00 UTC, sergiy-skalelabs commented on src/imaTx.ts
> +export declare type TPayedCallMethodArgument = any;
Here it's honest `any`. It's any argument of any method on any Ethereum-like network

2024-03-27 17:00 UTC, sergiy-skalelabs commented on src/loopWorker.ts
> +        function( joMessage: state.TLoadedJSON, joAnswer: any,
Here it's more-less honest `any`

2024-04-16 12:38 UTC, DmytroNazarenko approved these changes

2024-04-29 10:50 UTC, merged