ticket-3 much metter async calls
skalenetwork/ima-agent pull request #23
Opened 2023-11-17 17:41 UTC by sergiy-skalelabs

Refactored asynchronous calls like JSON RPC everywhere. Much less code indenting. Lot of big functions split into smaller ones.
No performance changes introduced.
No new tests needed.

2023-11-20 15:47 UTC, DmytroNazarenko commented on src/bls.mjs
>          const iv = setInterval( function() {
Let's move it outside of Promise

2023-11-20 15:47 UTC, DmytroNazarenko commented on src/imaCore.mjs
>  async function handleAllMessagesSigning( optsTransfer ) {
Convert to raw function

2023-11-20 16:17 UTC, sergiy-skalelabs commented on src/bls.mjs
>          const iv = setInterval( function() {
Done

2023-11-20 16:21 UTC, sergiy-skalelabs commented on src/imaCore.mjs
>  async function handleAllMessagesSigning( optsTransfer ) {
Done

2023-11-20 16:23 UTC, DmytroNazarenko commented on src/main.mjs
>      };
line 441: make it await

2023-11-20 16:25 UTC, sergiy-skalelabs commented on src/main.mjs
>      };
Done

2023-11-20 17:25 UTC, DmytroNazarenko reviewed
* Move sleep function to separate file and import it where needed

2023-11-20 17:25 UTC, DmytroNazarenko commented on src/discoveryTools.mjs
Remove Promise from discoverSChainNetwork

2023-11-20 17:25 UTC, DmytroNazarenko commented on src/oracle.mjs
>      const promiseComplete = new Promise( ( resolve, reject ) => {
Remove Promise

2023-11-20 17:51 UTC, sergiy-skalelabs commented on src/discoveryTools.mjs
Done

2023-11-20 17:51 UTC, sergiy-skalelabs commented on src/oracle.mjs
>      const promiseComplete = new Promise( ( resolve, reject ) => {
Done

2023-11-22 10:59 UTC, sergiy-skalelabs commented on src/discoveryTools.mjs
Done

2023-11-22 11:00 UTC, sergiy-skalelabs commented on src/oracle.mjs
>      const promiseComplete = new Promise( ( resolve, reject ) => {
Done

2023-11-24 17:54 UTC, dmytrotkk approved these changes

2023-11-24 18:09 UTC, badrogger approved these changes

2023-11-24 18:37 UTC, DmytroNazarenko requested changes

2023-11-24 18:37 UTC, DmytroNazarenko commented on src/clpTools.mjs
> +            async function( joCall, err ) {
Can we retrieve this function out of `create`?

2023-11-24 18:37 UTC, DmytroNazarenko commented on src/main.mjs
> +            await discoveryTools.waitUntilSChainStarted().then( function() {
Then is unneeded

2023-11-24 19:01 UTC, sergiy-skalelabs commented on src/main.mjs
> +            await discoveryTools.waitUntilSChainStarted().then( function() {
Need some explanation. Did't got idea.

2023-11-24 19:08 UTC, sergiy-skalelabs commented on src/clpTools.mjs
> +            async function( joCall, err ) {
We can, but I left it as is because it's 10 lines function.

2023-11-24 19:08 UTC, sergiy-skalelabs commented on src/main.mjs
> +            await discoveryTools.waitUntilSChainStarted().then( function() {
Removed, modified

2023-11-24 19:09 UTC, DmytroNazarenko approved these changes

2023-11-24 20:16 UTC, merged